164949 - Split photo API calls into separate calls
DEFRA/ivory pull request #297
Opened 2023-04-18 18:39 UTC by Harsh291104

- Refactored the code to update each additional photo in the separate Odata call

2023-04-19 09:12 UTC, ben-sagar requested changes
Need to include the first photo in this approach as well as the additional ones.

Also consider using binary data to be consistent with the way additional documents are handled.

Plus, maybe consider using `Promise.all` to make avoid sequential waits on I/O.

2023-04-21 15:45 UTC, Harsh291104 commented on server/routes/save-record.route.js
> +const _updateAdditionalPhotos = async (request, id, isSection2) => {
Done.

2023-04-21 15:46 UTC, Harsh291104 commented on server/routes/save-record.route.js
> +      await ODataService.updateRecord(id, additionalPhoto, isSection2)
bundled all patching commands in Promise.all() with logging message in case of both photos and documents.

2023-04-21 15:46 UTC, Harsh291104 commented on server/routes/save-record.route.js
> +      await ODataService.updateRecord(id, additionalPhoto, isSection2)
It is updated as it is done in updateRecordAttachments

2023-04-24 08:32 UTC, ben-sagar requested changes
Just need to remove the console logging and let the application-level error-handling deal with any issues

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
> +      console.log(`Patching URL: [${url}]`)
There shouldn't be `console.log` commands in the code - this should be removed

(I think this line had been left in erroneously from earlier development)

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
> +      console.log('All Photos Patched successfully:')
The application has logging, we shouldn't be logging to the console

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
> +      console.log('Error occurred while patching photos', error)
The application has logging and error handling, we shouldn't need to log to the console or catch the error here

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
>        console.log(`Patching URL: [${url}]`)
There shouldn't be `console.log` commands in the code - this should be removed

(I think this line had been left in erroneously from earlier development)

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
> +      console.log('All supporting documents patched successfully:')
The application has logging, we shouldn't be logging to the console

2023-04-24 08:32 UTC, ben-sagar commented on server/services/odata.service.js
> +      console.log('Error occurred while patching supporting documents', error)
The application has logging and error handling, we shouldn't need to log to the console or catch the error here

2023-04-24 11:28 UTC, ben-sagar requested changes

2023-04-24 11:28 UTC, ben-sagar commented on server/routes/save-record.route.js
> +  if (photos && photos.files && photos.files.length > 1) {
This should be testing for greater than zero photos, not greater than one - it might be a good idea to have a test for this?

2023-04-24 12:48 UTC, ben-sagar approved these changes

2023-04-24 13:12 UTC, merged