Ivory 307 user provides name and email
DEFRA/ivory pull request #30
Opened 2021-04-20 12:33 UTC by duncannixon

IVORY 307 - User provides name and email

Includes use of new form-layout.html

2021-04-20 15:48 UTC, Jozzey requested changes
Excellent work, all looks very good.
Just one minor thing, could you add a link to the Home page for the new "Who owns the item" page for easy access until the application is more whole.

2021-04-20 17:01 UTC, dgretho approved these changes

2021-04-21 07:18 UTC, duncannixon commented on server/routes/who-owns-the-item.route.js
> +    } else {
Fair enough, fixed.

2021-04-21 07:18 UTC, duncannixon commented on server/routes/user-details/owner/contact-details.route.js
> +    } else {
Fair enough, fixed.

2021-04-21 07:18 UTC, duncannixon commented
Added a link to the Home page for the new "Who owns the item" page

2021-04-21 08:57 UTC, Jozzey approved these changes
All good, thanks.

2021-04-21 08:58 UTC, merged